
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 11:46:59 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int D = 14;
  public static final int RO = 8;
  public static final int C = 12;
  public static final int INT = 2;
  public static final int SC = 11;
  public static final int U = 6;
  public static final int CM = 10;
  public static final int S = 5;
  public static final int EQ = 13;
  public static final int EOF = 0;
  public static final int RC = 9;
  public static final int ASS = 15;
  public static final int error = 1;
  public static final int G = 4;
  public static final int E = 3;
  public static final int WORD = 7;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("D");
		TT[8]=new String("RO");
		TT[12]=new String("C");
		TT[2]=new String("INT");
		TT[11]=new String("SC");
		TT[6]=new String("U");
		TT[10]=new String("CM");
		TT[5]=new String("S");
		TT[13]=new String("EQ");
		TT[0]=new String("EOF");
		TT[9]=new String("RC");
		TT[15]=new String("ASS");
		TT[1]=new String("error");
		TT[4]=new String("G");
		TT[3]=new String("E");
		TT[7]=new String("WORD");
	}
public String getTT(int i){return TT[i];}
}
