
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 02 18:33:01 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 9;
  public static final int AND = 14;
  public static final int PLUS = 10;
  public static final int INT = 27;
  public static final int OR = 15;
  public static final int THEN = 24;
  public static final int EQUAL = 12;
  public static final int CM = 3;
  public static final int CL = 2;
  public static final int DATE = 18;
  public static final int S = 4;
  public static final int RO = 6;
  public static final int NOT = 16;
  public static final int NAME = 28;
  public static final int CODE = 17;
  public static final int DT = 5;
  public static final int RC = 7;
  public static final int EOF = 0;
  public static final int WHEN = 22;
  public static final int SEP = 25;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int BO = 8;
  public static final int START = 19;
  public static final int DONE = 23;
  public static final int VAR = 21;
  public static final int MOVE = 20;
  public static final int DIF = 13;
  public static final int UMINUS = 26;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("BC");
		TT[14]=new String("AND");
		TT[10]=new String("PLUS");
		TT[27]=new String("INT");
		TT[15]=new String("OR");
		TT[24]=new String("THEN");
		TT[12]=new String("EQUAL");
		TT[3]=new String("CM");
		TT[2]=new String("CL");
		TT[18]=new String("DATE");
		TT[4]=new String("S");
		TT[6]=new String("RO");
		TT[16]=new String("NOT");
		TT[28]=new String("NAME");
		TT[17]=new String("CODE");
		TT[5]=new String("DT");
		TT[7]=new String("RC");
		TT[0]=new String("EOF");
		TT[22]=new String("WHEN");
		TT[25]=new String("SEP");
		TT[11]=new String("MINUS");
		TT[1]=new String("error");
		TT[8]=new String("BO");
		TT[19]=new String("START");
		TT[23]=new String("DONE");
		TT[21]=new String("VAR");
		TT[20]=new String("MOVE");
		TT[13]=new String("DIF");
		TT[26]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
