
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 01 09:53:35 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CT = 19;
  public static final int AND = 13;
  public static final int PLUS = 9;
  public static final int INT = 25;
  public static final int OR = 14;
  public static final int UMINUS2 = 30;
  public static final int EQUAL = 12;
  public static final int CM = 3;
  public static final int CL = 2;
  public static final int STAR = 11;
  public static final int S = 4;
  public static final int RO = 5;
  public static final int NOT = 15;
  public static final int CF = 18;
  public static final int TRUE = 27;
  public static final int SV = 20;
  public static final int RC = 6;
  public static final int SO = 7;
  public static final int EOF = 0;
  public static final int EV = 17;
  public static final int FALSE = 28;
  public static final int SEP = 24;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int SC = 8;
  public static final int TK3 = 23;
  public static final int TK2 = 22;
  public static final int VAR = 26;
  public static final int TK1 = 21;
  public static final int UMINUS = 29;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[19]=new String("CT");
		TT[13]=new String("AND");
		TT[9]=new String("PLUS");
		TT[25]=new String("INT");
		TT[14]=new String("OR");
		TT[30]=new String("UMINUS2");
		TT[12]=new String("EQUAL");
		TT[3]=new String("CM");
		TT[2]=new String("CL");
		TT[11]=new String("STAR");
		TT[4]=new String("S");
		TT[5]=new String("RO");
		TT[15]=new String("NOT");
		TT[18]=new String("CF");
		TT[27]=new String("TRUE");
		TT[20]=new String("SV");
		TT[6]=new String("RC");
		TT[7]=new String("SO");
		TT[0]=new String("EOF");
		TT[17]=new String("EV");
		TT[28]=new String("FALSE");
		TT[24]=new String("SEP");
		TT[10]=new String("MINUS");
		TT[1]=new String("error");
		TT[16]=new String("EQ");
		TT[8]=new String("SC");
		TT[23]=new String("TK3");
		TT[22]=new String("TK2");
		TT[26]=new String("VAR");
		TT[21]=new String("TK1");
		TT[29]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
