
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 14 16:34:23 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int D = 9;
  public static final int RO = 4;
  public static final int C = 6;
  public static final int A = 2;
  public static final int V = 3;
  public static final int EOF = 0;
  public static final int RC = 5;
  public static final int error = 1;
  public static final int RS = 8;
  public static final int IS = 7;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("D");
		TT[4]=new String("RO");
		TT[6]=new String("C");
		TT[2]=new String("A");
		TT[3]=new String("V");
		TT[0]=new String("EOF");
		TT[5]=new String("RC");
		TT[1]=new String("error");
		TT[8]=new String("RS");
		TT[7]=new String("IS");
	}
public String getTT(int i){return TT[i];}
}
