
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 11:31:36 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C = 13;
  public static final int INT = 2;
  public static final int IP = 4;
  public static final int TIME = 8;
  public static final int FILE = 3;
  public static final int SERVER = 6;
  public static final int CM = 12;
  public static final int DATA = 7;
  public static final int S = 14;
  public static final int DATE_STAMP = 10;
  public static final int BITRATE = 9;
  public static final int EOF = 0;
  public static final int LIST = 5;
  public static final int TIME_STAMP = 11;
  public static final int error = 1;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("C");
		TT[2]=new String("INT");
		TT[4]=new String("IP");
		TT[8]=new String("TIME");
		TT[3]=new String("FILE");
		TT[6]=new String("SERVER");
		TT[12]=new String("CM");
		TT[7]=new String("DATA");
		TT[14]=new String("S");
		TT[10]=new String("DATE_STAMP");
		TT[9]=new String("BITRATE");
		TT[0]=new String("EOF");
		TT[5]=new String("LIST");
		TT[11]=new String("TIME_STAMP");
		TT[1]=new String("error");
	}
public String getTT(int i){return TT[i];}
}
