
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 04 11:58:50 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DST = 15;
  public static final int PLUS = 9;
  public static final int CM = 3;
  public static final int QUOT = 23;
  public static final int IN = 17;
  public static final int CL = 2;
  public static final int STAR = 10;
  public static final int S = 4;
  public static final int EMAIL = 14;
  public static final int RO = 5;
  public static final int RC = 6;
  public static final int SO = 7;
  public static final int EOF = 0;
  public static final int VL = 16;
  public static final int SEP = 19;
  public static final int error = 1;
  public static final int EQ = 11;
  public static final int SC = 8;
  public static final int WR = 18;
  public static final int TK2 = 13;
  public static final int VAR = 22;
  public static final int TK1 = 12;
  public static final int DOUBLE = 21;
  public static final int UMINUS = 20;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("DST");
		TT[9]=new String("PLUS");
		TT[3]=new String("CM");
		TT[23]=new String("QUOT");
		TT[17]=new String("IN");
		TT[2]=new String("CL");
		TT[10]=new String("STAR");
		TT[4]=new String("S");
		TT[14]=new String("EMAIL");
		TT[5]=new String("RO");
		TT[6]=new String("RC");
		TT[7]=new String("SO");
		TT[0]=new String("EOF");
		TT[16]=new String("VL");
		TT[19]=new String("SEP");
		TT[1]=new String("error");
		TT[11]=new String("EQ");
		TT[8]=new String("SC");
		TT[18]=new String("WR");
		TT[13]=new String("TK2");
		TT[22]=new String("VAR");
		TT[12]=new String("TK1");
		TT[21]=new String("DOUBLE");
		TT[20]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
