
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 02 15:24:03 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OX = 11;
  public static final int PLUS = 7;
  public static final int INT = 20;
  public static final int CD2 = 10;
  public static final int M2 = 14;
  public static final int CD1 = 9;
  public static final int CLS = 12;
  public static final int CM = 3;
  public static final int M1 = 13;
  public static final int CL = 2;
  public static final int T = 16;
  public static final int S = 4;
  public static final int RO = 5;
  public static final int RC = 6;
  public static final int F = 17;
  public static final int FLOAT = 19;
  public static final int EOF = 0;
  public static final int SEP = 18;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int MAX = 15;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[11]=new String("OX");
		TT[7]=new String("PLUS");
		TT[20]=new String("INT");
		TT[10]=new String("CD2");
		TT[14]=new String("M2");
		TT[9]=new String("CD1");
		TT[12]=new String("CLS");
		TT[3]=new String("CM");
		TT[13]=new String("M1");
		TT[2]=new String("CL");
		TT[16]=new String("T");
		TT[4]=new String("S");
		TT[5]=new String("RO");
		TT[6]=new String("RC");
		TT[17]=new String("F");
		TT[19]=new String("FLOAT");
		TT[0]=new String("EOF");
		TT[18]=new String("SEP");
		TT[8]=new String("MINUS");
		TT[1]=new String("error");
		TT[15]=new String("MAX");
	}
public String getTT(int i){return TT[i];}
}
