
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 21 12:15:59 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUS = 10;
  public static final int SCVAR = 3;
  public static final int S = 8;
  public static final int RO = 16;
  public static final int END = 18;
  public static final int EXP = 15;
  public static final int RC = 17;
  public static final int uminus = 19;
  public static final int SO = 5;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int C = 7;
  public static final int DIV = 13;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int MIN = 11;
  public static final int SC = 6;
  public static final int MUL = 12;
  public static final int SCPR = 14;
  public static final int VCVAR = 4;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[10]=new String("PLUS");
		TT[3]=new String("SCVAR");
		TT[8]=new String("S");
		TT[16]=new String("RO");
		TT[18]=new String("END");
		TT[15]=new String("EXP");
		TT[17]=new String("RC");
		TT[19]=new String("uminus");
		TT[5]=new String("SO");
		TT[0]=new String("EOF");
		TT[2]=new String("NUMBER");
		TT[7]=new String("C");
		TT[13]=new String("DIV");
		TT[1]=new String("error");
		TT[9]=new String("EQ");
		TT[11]=new String("MIN");
		TT[6]=new String("SC");
		TT[12]=new String("MUL");
		TT[14]=new String("SCPR");
		TT[4]=new String("VCVAR");
	}
public String getTT(int i){return TT[i];}
}
