
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 30 19:59:01 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CODE = 10;
  public static final int INT = 12;
  public static final int STR = 14;
  public static final int HOUR = 9;
  public static final int CM = 4;
  public static final int S = 5;
  public static final int CL = 3;
  public static final int EOF = 0;
  public static final int USRCODE = 15;
  public static final int EURO = 8;
  public static final int ARROW = 2;
  public static final int SEP = 11;
  public static final int AUCTION = 6;
  public static final int error = 1;
  public static final int PRD = 16;
  public static final int MIN = 7;
  public static final int FLOAT = 13;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[10]=new String("CODE");
		TT[12]=new String("INT");
		TT[14]=new String("STR");
		TT[9]=new String("HOUR");
		TT[4]=new String("CM");
		TT[5]=new String("S");
		TT[3]=new String("CL");
		TT[0]=new String("EOF");
		TT[15]=new String("USRCODE");
		TT[8]=new String("EURO");
		TT[2]=new String("ARROW");
		TT[11]=new String("SEP");
		TT[6]=new String("AUCTION");
		TT[1]=new String("error");
		TT[16]=new String("PRD");
		TT[7]=new String("MIN");
		TT[13]=new String("FLOAT");
	}
public String getTT(int i){return TT[i];}
}
