
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jul 04 18:59:43 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 13;
  public static final int INIT = 20;
  public static final int PLUS = 9;
  public static final int INT = 32;
  public static final int OR = 14;
  public static final int EQUAL = 12;
  public static final int CM = 2;
  public static final int QUOT = 29;
  public static final int S = 3;
  public static final int RO = 5;
  public static final int NOT = 15;
  public static final int NAME = 30;
  public static final int DT = 4;
  public static final int CODE = 16;
  public static final int DO = 23;
  public static final int RC = 6;
  public static final int NUMBER = 18;
  public static final int SO = 7;
  public static final int EOF = 0;
  public static final int WHEN = 22;
  public static final int HOUR = 17;
  public static final int SEP = 19;
  public static final int MINUS = 10;
  public static final int PRINT = 27;
  public static final int CASE = 25;
  public static final int error = 1;
  public static final int ATT = 31;
  public static final int EQ = 11;
  public static final int SC = 8;
  public static final int DEFAULT = 21;
  public static final int DONE = 24;
  public static final int NEXT = 26;
  public static final int UMINUS = 28;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("AND");
		TT[20]=new String("INIT");
		TT[9]=new String("PLUS");
		TT[32]=new String("INT");
		TT[14]=new String("OR");
		TT[12]=new String("EQUAL");
		TT[2]=new String("CM");
		TT[29]=new String("QUOT");
		TT[3]=new String("S");
		TT[5]=new String("RO");
		TT[15]=new String("NOT");
		TT[30]=new String("NAME");
		TT[4]=new String("DT");
		TT[16]=new String("CODE");
		TT[23]=new String("DO");
		TT[6]=new String("RC");
		TT[18]=new String("NUMBER");
		TT[7]=new String("SO");
		TT[0]=new String("EOF");
		TT[22]=new String("WHEN");
		TT[17]=new String("HOUR");
		TT[19]=new String("SEP");
		TT[10]=new String("MINUS");
		TT[27]=new String("PRINT");
		TT[25]=new String("CASE");
		TT[1]=new String("error");
		TT[31]=new String("ATT");
		TT[11]=new String("EQ");
		TT[8]=new String("SC");
		TT[21]=new String("DEFAULT");
		TT[24]=new String("DONE");
		TT[26]=new String("NEXT");
		TT[28]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}
