
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 22:03:55 CEST 2017
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.HashMap;
import java.util.ArrayList;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Sat Jun 24 22:03:55 CEST 2017
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\031\000\002\002\004\000\002\003\005\000\002\004" +
    "\011\000\002\004\011\000\002\005\002\000\002\005\005" +
    "\000\002\006\004\000\002\007\005\000\002\007\004\000" +
    "\002\010\006\000\002\017\010\000\002\017\006\000\002" +
    "\011\005\000\002\012\002\000\002\012\004\000\002\013" +
    "\012\000\002\014\005\000\002\014\003\000\002\016\007" +
    "\000\002\016\006\000\002\021\003\000\002\015\010\000" +
    "\002\015\006\000\002\020\007\000\002\020\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\010\004\ufffd\005\ufffd\006\ufffd\001\002\000" +
    "\010\004\107\005\106\006\105\001\002\000\004\002\104" +
    "\001\002\000\004\007\007\001\002\000\004\027\064\001" +
    "\002\000\004\007\011\001\002\000\006\010\ufff4\027\ufff4" +
    "\001\002\000\004\002\000\001\002\000\006\010\014\027" +
    "\020\001\002\000\004\020\050\001\002\000\006\010\ufff3" +
    "\027\ufff3\001\002\000\004\025\045\001\002\000\006\002" +
    "\ufff5\027\020\001\002\000\004\025\uffed\001\002\000\004" +
    "\025\022\001\002\000\004\011\024\001\002\000\006\015" +
    "\037\024\040\001\002\000\004\026\025\001\002\000\004" +
    "\022\026\001\002\000\004\027\030\001\002\000\010\014" +
    "\033\015\uffeb\024\uffeb\001\002\000\004\026\031\001\002" +
    "\000\004\013\032\001\002\000\010\014\uffe9\015\uffe9\024" +
    "\uffe9\001\002\000\004\027\034\001\002\000\004\026\035" +
    "\001\002\000\004\013\036\001\002\000\010\014\uffea\015" +
    "\uffea\024\uffea\001\002\000\006\002\uffef\027\uffef\001\002" +
    "\000\004\011\041\001\002\000\004\026\042\001\002\000" +
    "\004\022\043\001\002\000\004\027\030\001\002\000\010" +
    "\014\033\015\uffec\024\uffec\001\002\000\004\011\024\001" +
    "\002\000\006\015\047\024\040\001\002\000\006\002\uffee" +
    "\027\uffee\001\002\000\004\027\051\001\002\000\004\021" +
    "\052\001\002\000\004\020\053\001\002\000\004\027\054" +
    "\001\002\000\006\014\ufff0\021\ufff0\001\002\000\006\014" +
    "\056\021\057\001\002\000\004\027\061\001\002\000\004" +
    "\015\060\001\002\000\006\010\ufff2\027\ufff2\001\002\000" +
    "\006\014\ufff1\021\ufff1\001\002\000\006\007\ufffb\027\064" +
    "\001\002\000\004\027\064\001\002\000\004\016\065\001" +
    "\002\000\004\027\066\001\002\000\004\023\076\001\002" +
    "\000\006\014\070\017\071\001\002\000\004\027\072\001" +
    "\002\000\006\007\ufff8\027\ufff8\001\002\000\004\023\073" +
    "\001\002\000\004\026\074\001\002\000\004\012\075\001" +
    "\002\000\006\014\ufff7\017\ufff7\001\002\000\004\026\077" +
    "\001\002\000\004\012\100\001\002\000\006\014\ufff6\017" +
    "\ufff6\001\002\000\006\007\ufff9\027\ufff9\001\002\000\004" +
    "\027\064\001\002\000\006\007\ufffa\027\ufffa\001\002\000" +
    "\004\002\001\001\002\000\004\015\116\001\002\000\004" +
    "\015\111\001\002\000\004\015\110\001\002\000\012\004" +
    "\ufffc\005\ufffc\006\ufffc\007\ufffc\001\002\000\006\004\ufffd" +
    "\006\ufffd\001\002\000\006\004\107\006\113\001\002\000" +
    "\004\015\114\001\002\000\006\004\ufffd\007\ufffd\001\002" +
    "\000\006\004\107\007\uffff\001\002\000\006\004\ufffd\005" +
    "\ufffd\001\002\000\006\004\107\005\120\001\002\000\004" +
    "\015\121\001\002\000\006\004\ufffd\007\ufffd\001\002\000" +
    "\006\004\107\007\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\010\003\004\004\005\005\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\006\007\001\001" +
    "\000\006\007\061\010\062\001\001\000\004\011\011\001" +
    "\001\000\004\012\012\001\001\000\002\001\001\000\010" +
    "\013\014\016\016\021\015\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\021\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\022\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\026\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\020\043\001\001\000\002\001\001\000" +
    "\004\015\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\054\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\101\001\001\000\004\010\100" +
    "\001\001\000\002\001\001\000\004\017\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\102\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\111\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\114\001\001\000\002\001\001\000\004\005" +
    "\116\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\121\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 Tree= new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }



  public HashMap<String, HashMap<String, Integer>> car_info = new HashMap<String, HashMap<String, Integer>>();

  public int getLine() {
      if (((Symbol)stack.elementAt(tos)).left != -1){
          return ((Symbol)stack.elementAt(tos)).left+1;
      }else return -1;
  }
  // Return the column number of actual symbol
  public int getColumn() {
      if (((Symbol)stack.elementAt(tos)).left != -1){
          return ((Symbol)stack.elementAt(tos)).right+1;
      }else return -1;
  }

  public Object stack ( int position){
    // returns the object at the specified position // from the top (tos) of the stack
    return(((Symbol)stack.elementAt(tos+position)).value);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


    void Pl(String s){
      System.out.println(s);
      return;
    }
    void P(String s){
      System.out.print(s);
      return;
    }


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // l_drive_stats ::= NAME INT M 
            { parser.Tree.reduce(3,"l_drive_stats",0);
              HashMap RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                            RESULT = new HashMap<String, Double>();
                            RESULT.put(n, new Double(i)); 
              CUP$parser$result = new java_cup.runtime.Symbol(14/*l_drive_stats*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // l_drive_stats ::= l_drive_stats CM NAME INT M 
            { parser.Tree.reduce(5,"l_drive_stats",0);
              HashMap RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		HashMap l = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                            l.put(n, new Double(i));
                            RESULT = l; 
              CUP$parser$result = new java_cup.runtime.Symbol(14/*l_drive_stats*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // l_part ::= PART INT C l_drive_stats 
            { parser.Tree.reduce(4,"l_part",0);
              Double RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		HashMap l = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
                    HashMap<String, Integer> stats = parser.car_info.get((String)parser.stack(-5));
                    Double tot = 0.0;
                    for(HashMap.Entry e : ((HashMap<String, Integer>)l).entrySet()){
                      Double partial = (Double)e.getValue()/stats.get(e.getKey());
                      tot += partial;
                    }
                    RESULT = tot;
                    Pl("PART" + i + " " + tot + " s"); 
              CUP$parser$result = new java_cup.runtime.Symbol(11/*l_part*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // l_part ::= l_part PIPE PART INT C l_drive_stats 
            { parser.Tree.reduce(6,"l_part",0);
              Double RESULT = null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Double lp = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		HashMap l = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
                    HashMap<String, Integer> stats = parser.car_info.get((String)parser.stack(-7));
                    Double tot = 0.0;
                    for(HashMap.Entry e : ((HashMap<String, Integer>)l).entrySet()){
                      Double partial = (Double)e.getValue()/stats.get(e.getKey());
                      tot += partial;
                    }
                    lp += tot;
                    RESULT = lp;
                    Pl("PART" + i + " " + tot + " s"); 
              CUP$parser$result = new java_cup.runtime.Symbol(11/*l_part*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // name ::= NAME 
            { parser.Tree.reduce(1,"name",0);
              String RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = n; Pl(n); 
              CUP$parser$result = new java_cup.runtime.Symbol(15/*name*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // l_performance ::= name ARROW l_part S 
            { parser.Tree.reduce(4,"l_performance",0);
              Object[] RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Double l = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    RESULT = new Object[2];
                    RESULT[0] = n;
                    RESULT[1] = l;
                    Pl("TOTAL: " + RESULT[1] + " s"); 
              CUP$parser$result = new java_cup.runtime.Symbol(12/*l_performance*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // l_performance ::= l_performance name ARROW l_part S 
            { parser.Tree.reduce(5,"l_performance",0);
              Object[] RESULT = null;
		int lpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int lpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object[] lp = (Object[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Double l = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    Pl("TOTAL: " + l + " s");
                    if((Double)lp[1] > l){
                      lp[0] = n;
                      lp[1] = l;
                      RESULT = lp;
                    }
                    else{
                      RESULT = lp;
                    } 
              CUP$parser$result = new java_cup.runtime.Symbol(12/*l_performance*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // l_section ::= NAME 
            { parser.Tree.reduce(1,"l_section",0);
              Integer[] RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
                        HashMap<String, Integer> info = parser.car_info.get((String)parser.stack(-3));
                        Integer actual = info.get(n);
                        RESULT = new Integer[2];
                        RESULT[0] = actual;
                        RESULT[1] = actual; 
              CUP$parser$result = new java_cup.runtime.Symbol(10/*l_section*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // l_section ::= l_section CM NAME 
            { parser.Tree.reduce(3,"l_section",0);
              Integer[] RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer[] l = (Integer[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		
                        HashMap<String, Integer> info = parser.car_info.get((String)parser.stack(-5));
                        // l[0] = min l[1] = max
                        Integer actual = info.get(n);
                        if(l[1] < actual){
                          l[1] = actual;
                        }
                        if(l[0] > actual){
                          l[0] = actual;
                        }
                        RESULT = l; 
              CUP$parser$result = new java_cup.runtime.Symbol(10/*l_section*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // print ::= PRINT_M_M RO NAME RC RO l_section RC S 
            { parser.Tree.reduce(8,"print",0);
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer[] l = (Integer[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 Pl("MIN: " + l[0] + " MAX: " + l[1]); 
              CUP$parser$result = new java_cup.runtime.Symbol(9/*print*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // l_print ::= l_print print 
            { parser.Tree.reduce(2,"l_print",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*l_print*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // l_print ::= 
            { parser.Tree.reduce(0,"l_print",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*l_print*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // race_section ::= SEP l_print l_performance 
            { parser.Tree.reduce(3,"race_section",0);
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Object[] l = (Object[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 Pl("WINNER: " + l[0] + " " + l[1] + " s"); 
              CUP$parser$result = new java_cup.runtime.Symbol(7/*race_section*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // l_speed ::= NAME EQ INT MS 
            { parser.Tree.reduce(4,"l_speed",0);
              HashMap RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                                      RESULT = new HashMap<String, Integer>();
                                      RESULT.put(n, i); 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*l_speed*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // l_speed ::= l_speed CM NAME EQ INT MS 
            { parser.Tree.reduce(6,"l_speed",0);
              HashMap RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		HashMap l = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer i = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                                      l.put(n, i);
                                      RESULT = l; 
              CUP$parser$result = new java_cup.runtime.Symbol(13/*l_speed*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // car ::= NAME BO l_speed BC 
            { parser.Tree.reduce(4,"car",0);
              Object RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		HashMap l = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 parser.car_info.put(n,l); 
              CUP$parser$result = new java_cup.runtime.Symbol(6/*car*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // l_car ::= car car 
            { parser.Tree.reduce(2,"l_car",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*l_car*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // l_car ::= l_car car car 
            { parser.Tree.reduce(3,"l_car",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*l_car*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // car_section ::= SEP l_car 
            { parser.Tree.reduce(2,"car_section",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*car_section*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // tk1_l ::= tk1_l TK1 S 
            { parser.Tree.reduce(3,"tk1_l",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*tk1_l*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // tk1_l ::= 
            { parser.Tree.reduce(0,"tk1_l",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*tk1_l*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // header ::= tk1_l TK3 S tk1_l TK2 S tk1_l 
            { parser.Tree.reduce(7,"header",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*header*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // header ::= tk1_l TK2 S tk1_l TK3 S tk1_l 
            { parser.Tree.reduce(7,"header",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*header*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= header car_section race_section 
            { parser.Tree.reduce(3,"prog",1);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*prog*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

