
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 24 22:03:55 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 13;
  public static final int PIPE = 18;
  public static final int INT = 20;
  public static final int CM = 10;
  public static final int S = 11;
  public static final int RO = 14;
  public static final int NAME = 21;
  public static final int M = 9;
  public static final int MS = 8;
  public static final int RC = 15;
  public static final int EOF = 0;
  public static final int C = 16;
  public static final int SEP = 5;
  public static final int ARROW = 19;
  public static final int error = 1;
  public static final int EQ = 17;
  public static final int BO = 12;
  public static final int TK3 = 4;
  public static final int PRINT_M_M = 6;
  public static final int TK2 = 3;
  public static final int TK1 = 2;
  public static final int PART = 7;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[13]=new String("BC");
		TT[18]=new String("PIPE");
		TT[20]=new String("INT");
		TT[10]=new String("CM");
		TT[11]=new String("S");
		TT[14]=new String("RO");
		TT[21]=new String("NAME");
		TT[9]=new String("M");
		TT[8]=new String("MS");
		TT[15]=new String("RC");
		TT[0]=new String("EOF");
		TT[16]=new String("C");
		TT[5]=new String("SEP");
		TT[19]=new String("ARROW");
		TT[1]=new String("error");
		TT[17]=new String("EQ");
		TT[12]=new String("BO");
		TT[4]=new String("TK3");
		TT[6]=new String("PRINT_M_M");
		TT[3]=new String("TK2");
		TT[2]=new String("TK1");
		TT[7]=new String("PART");
	}
public String getTT(int i){return TT[i];}
}
